### ISSUE TITLE
Create a CAP-Based Application -INTERNAL ERROR  '_initial' of undefined

### ISSUE THREAD

**Issue by dongtianxiaozi** [sap-tutorials/Tutorials#18255]
Tutorials: https://developers.sap.com/tutorials/btp-app-create-cap-application.html
--------------------------

After run CDS watch, I open link 'http://localhost:4004/service/risk/Risks'. Below error is raised.

[INTERNAL ERROR] **TypeError: Cannot read property '_initial' of undefined**
    at Service.handle (C:\Sk_Code\sk_cap_nodejs_20220309\cpapp\node_modules\@sap\cds\lib\serve\Service-dispatch.js:55:29)
    at Service.dispatch (C:\Sk_Code\sk_cap_nodejs_20220309\cpapp\node_modules\@sap\cds\lib\serve\Service-dispatch.js:40:15)
    at Service.send (C:\Sk_Code\sk_cap_nodejs_20220309\cpapp\node_modules\@sap\cds\lib\serve\Service-api.js:42:17)
    at ApplicationService._handler (C:\Sk_Code\sk_cap_nodejs_20220309\cpapp\node_modules\@sap\cds\libx\_runtime\fiori\generic\read.js:1276:36)
    at next (C:\Sk_Code\sk_cap_nodejs_20220309\cpapp\node_modules\@sap\cds\lib\serve\Service-dispatch.js:74:36)
    at ApplicationService.<anonymous> (C:\Sk_Code\sk_cap_nodejs_20220309\cpapp\node_modules\@sap\cds\libx\_runtime\common\generic\auth.js:851:12)
    at next (C:\Sk_Code\sk_cap_nodejs_20220309\cpapp\node_modules\@sap\cds\lib\serve\Service-dispatch.js:74:36)
    at ApplicationService.handle (C:\Sk_Code\sk_cap_nodejs_20220309\cpapp\node_modules\@sap\cds\lib\serve\Service-dispatch.js:78:6)     
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async _readCollection (C:\Sk_Code\sk_cap_nodejs_20220309\cpapp\node_modules\@sap\cds\libx\_runtime\cds-services\adapter\odata-v4\handlers\read.js:270:19)

Write here how you think we can improve the tutorial ...

**Comment by manjuX** [comment]
Hi @dongtianxiaozi,

To help fix the issue, could you share the versions of modules installed? To find this you can run `cds version`.

Best Regards,
Manjunath

**Comment by dongtianxiaozi** [comment]
>
Dear Manjuath,

The version info is as below:
@sap/cds: 5.8.3
@sap/cds-compiler: 2.12.0
@sap/cds-dk: 4.8.2
@sap/cds-foss: 3.1.0
@sap/eslint-plugin-cds: 2.3.2
Node.js: v14.16.1

**Comment by manjuX** [comment]
Hi @dongtianxiaozi,

I tried to reproduce the error with Node.js v14 but it did not occur. Can you try to work through the tutorial with version v16 of Node.js? It is the version we recommend in our tutorial as well.

Best Regards,
Manjunath

**Comment by iwonahahn** [comment]
Hi @dongtianxiaozi,

We haven't heard from you in a while, so we are closing the issue. If you still have questions, feel free to open a new issue.

Best regards,
Iwona
