### ISSUE TITLE
Test SAP API Business Hub APIs with curl

### ISSUE THREAD

**Issue by veeraa83** [sap-tutorials/Tutorials#18694]
Tutorials: https://developers.sap.com/tutorials/hcp-abh-test-locally.html
--------------------------

Write here how you think we can improve the tutorial ...

**Comment by veeraa83** [comment]
Unable to execute the step2 Generate sample API call code of this tutorial.  Logged into api.sap.com using my trial credentials. 
Tried multiple times but could not generate the curl code snippet foe the API 
/CampaignCollection
Not only for curl, code snippet were not generated for any language.

I could see that code snippets for all the listed languages were generated for another API /CampaignCollection('{ObjectID}')

Looks like it is a bug for this API call alone.

PFA the attached screenshot.
![campaignGet](https://user-images.githubusercontent.com/8470543/183080673-bdc2759d-e3e0-488c-bf78-b67ad0f13f63.jpeg)

In the console, I could see the below error

ERROR TypeError: e.trim is not a function
    at default~modules-api-viewer-module-apiviewer-module~modules-event-viewer-eventviewer-module.18c0e0e329b5f32243b8.js:1:1341242
    at Map.forEach (<anonymous>)
    at e.sanitizeMap (default~modules-api-viewer-module-apiviewer-module~modules-event-viewer-eventviewer-module.18c0e0e329b5f32243b8.js:1:1341173)
    at e.getHTTPSnippet (default~modules-api-viewer-module-apiviewer-module~modules-event-viewer-eventviewer-module.18c0e0e329b5f32243b8.js:1:1345723)
    at e.generateHttpSnippet (default~modules-api-viewer-module-apiviewer-module~modules-event-viewer-eventviewer-module.18c0e0e329b5f32243b8.js:1:1444749)
    at e.selectTab (default~modules-api-viewer-module-apiviewer-module~modules-event-viewer-eventviewer-module.18c0e0e329b5f32243b8.js:1:1444901)
    at default~modules-api-viewer-module-apiviewer-module~modules-event-viewer-eventviewer-module.18c0e0e329b5f32243b8.js:1:1423693
    at Ia (vendor.00dfccf9d23026ebf12d.js:1:281831)
    at i (vendor.00dfccf9d23026ebf12d.js:1:281991)
    at HTMLDivElement.<anonymous> (vendor.00dfccf9d23026ebf12d.js:1:659622)

**Comment by qmacro** [comment]
These issues are for problems with the tutorial content and flow itself, rather than for the products that are involved. May I suggest you head over to [SAP Community Q&A](https://answers.sap.com) to ask there, you may get a response from the product owners, and others will benefit too. Thanks!
