### ISSUE TITLE
Extend SAP SuccessFactors on SAP BTP, Cloud Foundry Environment

### ISSUE THREAD

**Issue by mofadili** [sap-tutorials/Tutorials#7347]
Tutorials: https://developers.sap.com/tutorials/btp-cf-ext-successfactors.html
--------------------------

Step 9: Deploy and run the extension application
Deployment does not work, app does crash at start with below log:

2021-12-22T15:04:50.28+0100 [APP/PROC/WEB/0] OUT   .   ____          _            __ _ _
   2021-12-22T15:04:50.28+0100 [APP/PROC/WEB/0] OUT  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
   2021-12-22T15:04:50.28+0100 [APP/PROC/WEB/0] OUT ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
   2021-12-22T15:04:50.28+0100 [APP/PROC/WEB/0] OUT  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
   2021-12-22T15:04:50.28+0100 [APP/PROC/WEB/0] OUT   '  |____| .__|_| |_|_| |_\__, | / / / /
   2021-12-22T15:04:50.28+0100 [APP/PROC/WEB/0] OUT  =========|_|==============|___/=/_/_/_/
   2021-12-22T15:04:50.28+0100 [APP/PROC/WEB/0] OUT  :: Spring Boot ::        (v2.2.1.RELEASE)
   2021-12-22T15:04:52.50+0100 [APP/PROC/WEB/0] OUT 2021-12-22 14:04:52.504  INFO 7 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
   2021-12-22T15:04:52.50+0100 [APP/PROC/WEB/0] OUT 2021-12-22 14:04:52.507  INFO 7 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.27]
   2021-12-22T15:04:52.57+0100 [APP/PROC/WEB/0] OUT 2021-12-22 14:04:52.577  INFO 7 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
   2021-12-22T15:04:53.52+0100 [APP/PROC/WEB/0] OUT 2021-12-22 14:04:53.527  INFO 7 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
   2021-12-22T15:04:53.54+0100 [APP/PROC/WEB/0] OUT 2021-12-22 14:04:53.548 ERROR 7 --- [           main] o.s.boot.SpringApplication               : Application run failed
   2021-12-22T15:04:53.54+0100 [APP/PROC/WEB/0] OUT org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'taskManagementController' defined in file [/home/vcap/app/BOOT-INF/classes/com/sap/core/extensions/taskmanagement/rest/TaskManagementController.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.sap.core.extensions.taskmanagement.rest.TaskManagementController]: Constructor threw exception; nested exception is java.lang.Error: Unresolved compilation problems:
   2021-12-22T15:04:53.54+0100 [APP/PROC/WEB/0] OUT     The method getToDoEntryName() is undefined for the type ToDoEntryV2DTO
   2021-12-22T15:04:53.54+0100 [APP/PROC/WEB/0] OUT     The method ok(T) in the type ResponseEntity is not applicable for the arguments (TaskRequestsDTO)
   2021-12-22T15:04:53.54+0100 [APP/PROC/WEB/0] OUT     The constructor TaskRequestsDTO(List<TaskRequestDTO>) is undefined
   2021-12-22T15:04:53.54+0100 [APP/PROC/WEB/0] OUT     The constructor TaskRequestDTO(ToDoEntryV2DTO, null) is undefined

.........

2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:582) ~[spring-context-5.3.4.jar:5.3.4]
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     at com.sap.core.extensions.taskmanagement.Application.main(Application.java:17) [classes/:na]
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_311]
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_311]
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_311]
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_311]
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [app/:na]
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [app/:na]
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [app/:na]
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [app/:na]
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.sap.core.extensions.taskmanagement.rest.TaskManagementController]: Constructor threw exception; nested exception is java.lang.Error: Unresolved compilation problems:
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     The method getToDoEntryName() is undefined for the type ToDoEntryV2DTO
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     The method ok(T) in the type ResponseEntity is not applicable for the arguments (TaskRequestsDTO)
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     The constructor TaskRequestsDTO(List<TaskRequestDTO>) is undefined
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     The constructor TaskRequestDTO(ToDoEntryV2DTO, null) is undefined
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:225) ~[spring-beans-5.3.4.jar:5.3.4]
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.3.4.jar:5.3.4]
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311) ~[spring-beans-5.3.4.jar:5.3.4]
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     ... 27 common frames omitted
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT Caused by: java.lang.Error: Unresolved compilation problems:
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     The method getToDoEntryName() is undefined for the type ToDoEntryV2DTO
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     The method ok(T) in the type ResponseEntity is not applicable for the arguments (TaskRequestsDTO)
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     The constructor TaskRequestsDTO(List<TaskRequestDTO>) is undefined
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     The constructor TaskRequestDTO(ToDoEntryV2DTO, null) is undefined
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     at com.sap.core.extensions.taskmanagement.rest.TaskManagementController.<init>(TaskManagementController.java:39) ~[classes/:na]
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_311]
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_311]
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_311]
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_311]
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:212) ~[spring-beans-5.3.4.jar:5.3.4]
   2021-12-22T15:06:12.65+0100 [APP/PROC/WEB/0] OUT     ... 29 common frames omitted
   2021-12-22T15:06:12.69+0100 [APP/PROC/WEB/0] OUT Exit status 1
   2021-12-22T15:06:17.94+0100 [CELL/0] OUT Cell bd269a3e-25de-4dcc-b1e6-30f72ba90855 stopping instance 7dd31ce3-8e66-48d7-5a33-8b52
   2021-12-22T15:06:17.94+0100 [CELL/0] OUT Cell bd269a3e-25de-4dcc-b1e6-30f72ba90855 destroying container for instance 7dd31ce3-8e66-48d7-5a33-8b52
   2021-12-22T15:06:17.97+0100 [API/25] OUT Process has crashed with type: "web"
   2021-12-22T15:06:18.00+0100 [API/25] OUT App instance exited with guid d4875a3c-faca-413b-ab2c-0098df9c48d4 payload: {"instance"=>"7dd31ce3-8e66-48d7-5a33-8b52", "index"=>0, "cell_id"=>"bd269a3e-25de-4dcc-b1e6-30f72ba90855", "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 1", "crash_count"=>4, "crash_timestamp"=>1640181977939370928, "version"=>"038c8d6d-cc62-421c-a881-a7036dd44ab2"}
   2021-12-22T15:06:18.07+0100 [PROXY/0] OUT Exit status 137
   2021-12-22T15:06:18.34+0100 [CELL/0] OUT Cell bd269a3e-25de-4dcc-b1e6-30f72ba90855 successfully destroyed container for instance 7dd31ce3-8e66-48d7-5a33-8b52

**Comment by mofadili** [comment]
Hi team,

After reinstall of JDK 11.x, mvn clean and mvn install, the deploy process worked.

Thanks
